--
-- Birthplace and Realm data for HarnMaster
--

Nations = {
	["Altor"] = {
		["Amlacht Town"] = { society = "Tributary", pantheon = "Altic-Ivinian", language = "Altic" },
		["Lybath Town"] = { society = "Tributary", pantheon = "Altic", language = "Altic" },
		["West Alti Lands"] = { society = "Tribal", pantheon = "Altic", language = "Altic" },
		["East Alti Lands"] = { society = "Tribal", pantheon = "Altic", language = "Altic" },
	},
	["Azeryan"] = {
		["Ashon Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Azen Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Helen Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Ilis Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Kantreda Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Laema Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Lotmir Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Menkre Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Misonae Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Naliat Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Ontonas Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Ramien Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Sasala Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Skoraz Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Thonaru Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Tonatra Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Valenae Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Vedora Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Alam Gares Mil. Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Alam Loas Mil. Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Beronium Mil. Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Indaral Military Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Sanos Military Province"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Gothmir Gares March"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Gothmir Loas March"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Kalinelari March"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Tonatri Lands"] = { society = "Tribal", pantheon = "Tonatri", language = "Nasik Azeri" },
		["Principality Of Goris"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Grand Principality of Lankor"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik Azeri" },
		["Lankor Emhle"] = { society = "Tribal", pantheon = "Covenant", language = "Nasik Azeri" },
	},
	["Byria"] = {
		["Armala Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
		["Ayen Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
		["Bamen Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
		["Daria Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
		["Elonas Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
		["Inritha Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
		["Insulana Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
		["Kantranas Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
		["Kinis Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
		["Laselana Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
		["Moralas Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
		["Naran Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
		["Norva Province"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Byrian" },
	},
	["Chogoro-Mafani"] = {
		["Amvar Kingdom"] = { society = "Feudal", pantheon = "Mafani", language = "Pechalari" },
		["Boliafra League"] = { society = "Imperial", pantheon = "Mafani", language = "Mafani" },
		["Chifar League"] = { society = "Imperial", pantheon = "Mafani", language = "Mafani" },
		["Deluma Republic"] = { society = "Feudal-Imperial", pantheon = "Mafani", language = "Chogori" },
		["Genjes Kingdom"] = { society = "Feudal", pantheon = "Mafani", language = "Mafani" },
		["Lutra Kingdom"] = { society = "Feudal", pantheon = "Mafani", language = "Chogori" },
		["Serianapi League"] = { society = "Imperial", pantheon = "Mafani & Anzelorian ", language = "Shenti" },
	},
	["Dalkesh"] = {
		["Adesh Province"] = { society = "Imperial", pantheon = "Dalken", language = "Elbythian" },
		["Akamar Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Aninis Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Dehar Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Donolash Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Galpura Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Heponpura Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Khalik Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Khanesh Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Khedan Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Nagran Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Nalhaman Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Nathapura Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Onripura Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Resikhar Province"] = { society = "Imperial", pantheon = "Dalken", language = "Elbythian" },
		["Sobrash Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
		["Tibelos Province"] = { society = "Imperial", pantheon = "Dalken", language = "Dalken" },
	},
	["Emelrene"] = {
		["Quandas Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Emelan" },
		["Algram Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Emelan" },
		["Fandalon Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Emelan" },
		["Alwina Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Emelan" },
		["Malad Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Emelan" },
		["Berema Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Emelan" },
		["Ulama Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Emelan" },
		["Jerinala March"] = { society = "Feudal", pantheon = "West Venarian", language = "Emelan" },
		["Emhle Range"] = { society = "Tribal", pantheon = "Covenant", language = "Emhlen" },
	},
	["Hacherdad"] = {
		["Balshel Principality"] = { society = "Imperial", pantheon = "Hacherian", language = "Hacherian" },
		["Echrum Principality"] = { society = "Imperial", pantheon = "Hacherian", language = "Hacherian" },
		["Hacherul Principality"] = { society = "Imperial", pantheon = "Hacherian", language = "Hacherian" },
		["Kuladith Principality"] = { society = "Imperial", pantheon = "Hacherian", language = "Hacherian" },
		["Marshum Principality"] = { society = "Imperial", pantheon = "Hacherian", language = "Hacherian" },
		["Morchad Principality"] = { society = "Imperial", pantheon = "Hacherian", language = "Hacherian" },
		["Ocharim Principality"] = { society = "Imperial", pantheon = "Hacherian", language = "Hacherian" },
		["Shelum Principality"] = { society = "Imperial", pantheon = "Hacherian", language = "Hacherian" },
	},
	["Harbaal"] = {
		["Anval"] = { society = "Viking", pantheon = "Ivinian (mix)", language = "Harbaaler" },
		["Avastran"] = { society = "Viking", pantheon = "Ivinian (mix)", language = "Harbaaler" },
		["Gatenlund"] = { society = "Viking", pantheon = "Ivinian (mix)", language = "Harbaaler" },
		["Elgosa & Gildwaal"] = { society = "Viking", pantheon = "Ivinian (mix)", language = "Harbaaler" },
		["Gavrios"] = { society = "Viking", pantheon = "Ivinian (mix)", language = "Harbaaler" },
		["Geltheim"] = { society = "Viking", pantheon = "Ivinian (mix)", language = "Harbaaler" },
		["Ketania"] = { society = "Viking", pantheon = "Ivinian (mix)", language = "Harbaaler" },
		["Ledenheim"] = { society = "Viking", pantheon = "Ivinian (mix)", language = "Harbaaler" },
		["Lytheim"] = { society = "Viking", pantheon = "Ivinian (mix)", language = "Harbaaler" },
		["Padona"] = { society = "Viking", pantheon = "Ivinian (mix)", language = "Harbaaler" },
		["Saliom"] = { society = "Viking", pantheon = "Ivinian (mix)", language = "Harbaaler" },
		["Tonanby"] = { society = "Viking", pantheon = "Ivinian (mix)", language = "Harbaaler" },
		["Chelemby Kingdom"] = { society = "Tributary (Viking)", pantheon = "West Venarian", language = "Cheler" },
		["Yarla Lands"] = { society = "Tribal", pantheon = "Yarla", language = "Yarla" },
	},
	["Harn"] = {
		["Chybisa Kingdom"] = { society = "Feudal", pantheon = "West Venarian", language = "Harnic" },
		["Elder Realms"] = { society = "Feudal", pantheon = "West Venarian", language = "Jarin" },
		["Kaldor Kingdom"] = { society = "Feudal", pantheon = "West Venarian", language = "Harnic" },
		["Kanday Kingdom"] = { society = "Feudal", pantheon = "West Venarian", language = "Harnic" },
		["Melderyn Kingdom"] = { society = "Feudal", pantheon = "West Venarian", language = "Harnic" },
		["Orbaal Kingdom"] = { society = "Tributary", pantheon = "West Venarian", language = "Orbaaler" },
		["Orbaal Kingdom (subjugated Jarin)"] = { society = "Tributary", pantheon = "West Venarian", language = "Jarin" },
		["Rethem Kingdom"] = { society = "Feudal", pantheon = "West Venarian", language = "Harnic" },
		["Thardic Republic"] = { society = "Feudal-Imperial", pantheon = "West Venarian", language = "Harnic" },
		["Adaenum"] = { society = "Jarin-Adaenian", pantheon = "Barbarian", language = "Jarin" },
		["Anoa"] = { society = "Jarin-Nuthelan", pantheon = "Barbarian", language = "Jarin" },
		["Bujoc"] = { society = "Harnic-Anadel", pantheon = "Barbarian", language = "Harnic" },
		["Chelni"] = { society = "Harnic-Chohar", pantheon = "Barbarian", language = "Harnic" },
		["Chymak"] = { society = "Chyma", pantheon = "Barbarian", language = "Chyma" },
		["Equani"] = { society = "Jarin-Peranic", pantheon = "Barbarian", language = "Jarin" },
		["Gozyda"] = { society = "Harnic-Uphari", pantheon = "Barbarian", language = "Harnic" },
		["Hodiri"] = { society = "Harnic-Chohar", pantheon = "Barbarian", language = "Harnic" },
		["Kabloqui"] = { society = "Jarin-Peranic", pantheon = "Barbarian", language = "Jarin" },
		["Kamaki"] = { society = "Kamakin", pantheon = "Barbarian", language = "Kamakin" },
		["Kath"] = { society = "Harnic-Uphari", pantheon = "Barbarian", language = "Harnic" },
		["Kubora"] = { society = "Jarin-Peranic", pantheon = "Barbarian", language = "Jarin" },
		["Pagaelin"] = { society = "Harnic", pantheon = "Barbarian", language = "Harnic" },
		["Solori"] = { society = "Harnic-Solora", pantheon = "Barbarian", language = "Harnic" },
		["Taelda"] = { society = "Jarin-Nuthelan", pantheon = "Barbarian", language = "Jarin" },
		["Tulwyn"] = { society = "Harnic-Uphari", pantheon = "Barbarian", language = "Harnic" },
		["Urdu"] = { society = "Jarin-Peranic", pantheon = "Barbarian", language = "Jarin" },
		["Ymodi"] = { society = "Jarin-Nuthelan", pantheon = "Barbarian", language = "Jarin" },
	},
	["Hepekeria"] = {
		["Air Sub-nation"] = { society = "Tribal", pantheon = "Numec", language = "Numer" },
		["Azuwirat Lands"] = { society = "Tribal", pantheon = "Numec", language = "Numer" },
		["Iwil Sub-nation"] = { society = "Tribal", pantheon = "Numec", language = "Numer" },
		["Durqa Awrim Lands"] = { society = "Tribal", pantheon = "Numec", language = "Numer" },
		["Lawata Sub-nation"] = { society = "Tribal", pantheon = "Numec", language = "Numer" },
		["Naj'er Sub-nation"] = { society = "Tribal", pantheon = "Numec", language = "Numer" },
		["Udan Sub-nation"] = { society = "Tribal", pantheon = "Numec", language = "Numer" },
		["Charinatre Kingdom"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Korlic" },
		["Dysor Kingdom"] = { society = "Feudal-Imperial", pantheon = "Azeri or Numec", language = "Korlic" },
		["Gemena Kingdom"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Korlic" },
		["Isynen Area"] = { society = "City-State", pantheon = "Numec-Venarian", language = "Korlic" },
		["Korlua Kingdom"] = { society = "Tributary", pantheon = "Ivin.-Numec", language = "Ivinian" },
		["Menema Kingdom"] = { society = "Tributary", pantheon = "Azeri", language = "Nasik" },
		["Vitho Kingdom"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Nasik" },
		["Xerium Kingdom"] = { society = "Imperial", pantheon = "Azeri", language = "Nasik" },
		["Buqdin Lands"] = { society = "Tribal", pantheon = "Buqdin", language = "Buqdin" },
		["Dalani Lands"] = { society = "Tribal", pantheon = "Dalani", language = "Dalani" },
		["Bothisa Area"] = { society = "City-State", pantheon = "Numec", language = "Falani" },
		["Silgora Area"] = { society = "City-State", pantheon = "Numec", language = "Falani" },
		["Thubeliz Area"] = { society = "City-State", pantheon = "Numec", language = "Falani" },
		["Falanian Towns"] = { society = "Imperial", pantheon = "Numec", language = "Falani" },
		["Falanian Colonies"] = { society = "Imperial", pantheon = "Numec", language = "Falani" },
		["Tribal Falani Lands"] = { society = "Tribal", pantheon = "Numec", language = "Falani" },
	},
	["Hurisea"] = {
		["Antol Principality"] = { society = "Tributary", pantheon = "Quarphic", language = "Hurisean" },
		["Beldira Principality"] = { society = "Tributary", pantheon = "Quarphic", language = "Hurisean" },
		["Chegen Principality"] = { society = "Tributary", pantheon = "West Venarian-Quarphic", language = "Hurisean" },
		["Dechen Principality"] = { society = "Tributary", pantheon = "Quarphic", language = "Hurisean" },
		["Ekedon Principality"] = { society = "Tributary", pantheon = "Quarphic", language = "Hurisean" },
		["Figend Principality"] = { society = "Tributary", pantheon = "Ivinian-Quarphic", language = "Hurisean" },
		["Helgen Principality"] = { society = "Tributary", pantheon = "Ivinian-Quarphic", language = "Hurisean" },
		["Jondes Principality"] = { society = "Tributary", pantheon = "Quarphic", language = "Hurisean" },
		["Ogened Principality"] = { society = "Tributary", pantheon = "West Venarian-Quarphic", language = "Hurisean" },
		["Ponel Principality"] = { society = "Tributary", pantheon = "Quarphic", language = "Hurisean" },
		["Unten Principality"] = { society = "Tributary", pantheon = "Ivinian-Quarphic", language = "Hurisean" },
		["Minor Principalities"] = { society = "Tributary", pantheon = "Quarphic", language = "Hurisean" },
	},
	["Ivinia"] = {
		["Balisheim"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Gelemar"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Gilbenmark"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Lokemheim"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Seldenbaal"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Beshea Kingdom"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Eldeskaal Kingdom"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Govyna Great Kingdom"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Ibanvaal Kingdom"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Jarenmark Kingdom"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Lokis Kingdom"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Menglana Kingdom"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Rogna Kingdom"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Tavu Kingdom"] = { society = "Viking", pantheon = "Ivinian", language = "Ivinian" },
		["Yarili Lands"] = { society = "Tribal", pantheon = "Yarili", language = "Yarili" },
	},
	["Karejia"] = {
		["Ajygal Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Arketh Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Nasik Azeri-island" },
		["Durien Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Gilech Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Elbythian" },
		["Helas Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Horitar Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Ichenyah Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Kolomir Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Elbythian" },
		["Livelis Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Narolis Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Phanosia Mil. Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Rykal Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Shelon Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Tazach Military Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
	},
	["Ketarh-Beshakan"] = {
		["Anil Ketari Lands"] = { society = "Tribal", pantheon = "Ketari", language = "Anil Ketari" },
		["Ketari Lands"] = { society = "Tribal", pantheon = "Ketari", language = "Ketari" },
		["Besha Lands"] = { society = "Tribal", pantheon = "Besha", language = "Besha" },
		["Namardim Lands"] = { society = "Tribal", pantheon = "Besha", language = "Namardi" },
	},
	["Northern Anzeloria"] = {
		["Neshai Lands"] = { society = "Tribal", pantheon = "Anzelorian", language = "Neshai" },
		["Pechalari Lands"] = { society = "Tribal", pantheon = "Anzelorian", language = "Pechalari" },
		["Sogoranele City-State"] = { society = "Imperial", pantheon = "Anzelorian", language = "Pechalari" },
		["Eastern Tuvaran Lands"] = { society = "Tribal", pantheon = "Anzelorian", language = "Tuvaran" },
		["Southern Tuvaran Lands"] = { society = "Tribal", pantheon = "Anzelorian", language = "Tuvaran" },
		["Western Tuvaran Lands"] = { society = "Tribal", pantheon = "Anzelorian", language = "Tuvaran" },
	},
	["Palithane"] = {
		["Athamas Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Batana Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Palithaner" },
		["Gavas Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Palithaner" },
		["Liguno Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Palithaner" },
		["Luindar Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Palithaner" },
		["Norimar Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Palithaner" },
		["Skagia Shire"] = { society = "Feudal", pantheon = "West Venarian", language = "Palithaner" },
		["Tamanias March"] = { society = "Feudal", pantheon = "West Venarian", language = "Palithaner" },
		["Luinde Emhle Lands"] = { society = "Tribal", pantheon = "Kuelrhyn", language = "Emhlen" },
	},
	["Quarphor"] = {
		["Aulumon Principality"] = { society = "Tributary", pantheon = "Quarphic", language = "Quarphic" },
		["Ekenon Principality"] = { society = "Tributary", pantheon = "Quarphic", language = "Quarphic" },
		["Kvarfent Principality"] = { society = "Tributary", pantheon = "Quarphic", language = "Quarphic" },
		["Orlet Town"] = { society = "Tributary", pantheon = "Quarphic", language = "Quarphic" },
		["Vaben Principality"] = { society = "Tributary", pantheon = "Quarphic", language = "Quarphic" },
		["Minor Quarphic States"] = { society = "Tributary", pantheon = "Quarphic", language = "Quarphic" },
		["Eastern"] = { society = "Tribal", pantheon = "Quarphic", language = "Quarphic" },
		["Northern"] = { society = "Tribal", pantheon = "Quarphic", language = "Quarphic" },
		["Southern"] = { society = "Tribal", pantheon = "Quarphic", language = "Quarphic" },
		["Western"] = { society = "Tribal", pantheon = "Quarphic", language = "Quarphic" },
	},
	["Reksyna"] = {
		["Eastern Lands"] = { society = "Tribal", pantheon = "Reksyni", language = "Reksyni" },
		["Northern Lands"] = { society = "Tribal", pantheon = "Reksyni", language = "Reksyni" },
		["Southern Lands"] = { society = "Tribal", pantheon = "Reksyni", language = "Reksyni" },
		["Western Lands"] = { society = "Tribal", pantheon = "Reksyni", language = "Reksyni" },
		["Mengolan Lands"] = { society = "Tribal", pantheon = "Mengolan", language = "Mengolan" },
	},
	["Shorkyne"] = {
		["Bodoe County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Meloda County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Pelodia County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Aneola County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Avan County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Dumala County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Hidel County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Istebinia County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Kitalin County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Nistone County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Falimae County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Chomu County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Kolare County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Loala County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Malpynia County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Netela County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Pilatha County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Sabinia County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Shaplane County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Kemol County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Montivel County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Quareld County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Elavona County"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Vadone"] = { society = "Feudal", pantheon = "West Venarian", language = "Shorka" },
		["Shorkyni Emhle Lands"] = { society = "Tribal", pantheon = "Kuelrhyn", language = "Emhlen" },
	},
	["Thonia"] = {
		["Inner Lands"] = { society = "Tribal", pantheon = "Anzelorian", language = "Thonian" },
		["Laker Lands"] = { society = "Tribal", pantheon = "Anzelorian", language = "Thonian" },
		["Mountain Lands"] = { society = "Tribal", pantheon = "Anzelorian", language = "Thonian" },
		["Northern Lands"] = { society = "Tribal", pantheon = "Anzelorian", language = "Thonian" },
		["Southern Lands"] = { society = "Tribal", pantheon = "Anzelorian", language = "Thonian" },
		["Western Lands"] = { society = "Tribal", pantheon = "Anzelorian", language = "Thonian" },
		["Arlanto Kingdom"] = { society = "Feudal-Imperial", pantheon = "Azeri", language = "Herei" },
		["Elanasi Lands (coastal)"] = { society = "Tribal", pantheon = "Elanasi", language = "Elanasi" },
		["Elanasi Lands (inland)"] = { society = "Tribal", pantheon = "Elanasi", language = "Elanasi" },
		["Herei Lands"] = { society = "Tribal", pantheon = "Herei", language = "Herei" },
	},
	["Trierzon"] = {
		["Agelos County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Amesuma County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Anfaldon County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Areshomes County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Baldeme County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Bodima County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Bomedus County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Chimas County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Devai County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Dovalin County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Enala County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Faldin Countyd"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Faleo County"] = { society = "Feudal", pantheon = "West Venarian", language = "Nasik Azeri" },
		["Gelamo County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Halmo County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Hedames County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Ilaska County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Ilbra County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Ilona County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Jaleda County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Janora County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Kogamin Countyd"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Korun County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Latima County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Magalia County"] = { society = "Feudal", pantheon = "West Venarian", language = "Nasik Azeri" },
		["Malagos County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Manas County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Mankonia County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Melesuma Countyd"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Nadamia County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Omegen County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Palama County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Peltane County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Perna County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Rindi County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Senedalo County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Stalfore Countyd"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Tamala County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Tashones County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Tengela County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Trabant Countyd"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Ubai Countyd"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Vedin County"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Zhoren Countyd"] = { society = "Feudal", pantheon = "West Venarian", language = "Trierzi" },
		["Trierzi Emhle Lands"] = { society = "Tribal", pantheon = "Kuelrhyn", language = "Emhlen" },
		["Tarkain Principality"] = { society = "Feudal", pantheon = "West Venarian", language = "Ivinian" },
	},
	["Umelria"] = {
		["Barath Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Erkyne Province"] = { society = "City-State", pantheon = "Azeri", language = "Urmech" },
		["Fegon Province"] = { society = "City-State", pantheon = "Azeri", language = "Urmech" },
		["Gelon Province"] = { society = "City-State", pantheon = "Azeri", language = "Urmech" },
		["Genoro Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Lekuria Province"] = { society = "City-State", pantheon = "Azeri", language = "Karejian" },
		["Parthias Province"] = { society = "City-State", pantheon = "Azeri", language = "Urmech" },
		["Rydaz Province"] = { society = "City-State", pantheon = "Azeri", language = "Urmech" },
		["Umeni Lands"] = { society = "Tribal", pantheon = "Umeni", language = "Umeni" },
	},
}
