-- 
-- Equipment Data
-- 

local aEquipmentData = {
    ["Arrow Bag (24)"] = { type = "Container", weight = 4, price = 48 },
    ["Backpack (30)"] = { type = "Container", weight = 4, price = 30 },
    ["Bag, Leather (15)"] = { type = "Container", weight = 2, price = 12 },
    ["Bandages (32)"] = { type = "Supplies", weight = 3, price = 24 },
    ["Bedroll"] = { type = "Equipment", weight = 4, price = 96 },
    ["Bedroll, Heavy"] = { type = "Equipment", weight = 10, price = 144 },
    ["Belt Pouch (5)"] = { type = "Container", weight = 0.5, price = 4 },
    ["Bow Case"] = { type = "Container", weight = 3, price = 18 },
    ["Blanket"] = { type = "Equipment", weight = 3, price = 132 },
    ["Flask (1 pt)"] = { type = "Container", weight = 0.5, price = 6 },
    ["Grappling Hook"] = { type = "Equipment", weight = 4, price = 18 },
    ["Herbs (retail)"] = { type = "Supplies", weight = 1, price = 0.25 },
    ["Lantern (1/8 pt)"] = { type = "Equipment", weight = 1, price = 12 },
    ["Lockpicks"] = { type = "Tools", weight = 1, price = 15 },
    ["Oil (1 pt)"] = { type = "Supplies", weight = 1, price = 1.5 },
    ["Pitons, Iron (6)"] = { type = "Equipment", weight = 2, price = 6 },
    ["Potion, Great"] = { type = "Equipment", weight = 1, price = 480 },
    ["Potion, Mild"] = { type = "Equipment", weight = 1, price = 16 },
    ["Potion, Strong"] = { type = "Equipment", weight = 1, price = 48 },
    ["Pouch, Buckram"] = { type = "Container", weight = 0.25, price = 7 },
    ["Purse, Silk"] = { type = "Container", weight = 0.1, price = 60 },
    ["Quiver (12)"] = { type = "Container", weight = 2, price = 8 },
    ["Quiver (24)"] = { type = "Container", weight = 3, price = 12 },
    ["Rations, Iron"] = { type = "Equipment", weight = 3, price = 3 },
    ["Rations, Standard"] = { type = "Equipment", weight = 3, price = 2 },
    ["Rope, Hemp, 1\", 50'"] = { type = "Equipment", weight = 12, price = 96 },
    ["Rope, Hemp, 1/2\", 50'"] = { type = "Equipment", weight = 4, price = 48 },
    ["Rope, Silk, 1/2\", 50'"] = { type = "Equipment", weight = 4, price = 1440 },
    ["Sack, Canvas (50)"] = { type = "Container", weight = 1, price = 24 },
    ["Sack, Canvas (20)"] = { type = "Container", weight = 0.5, price = 12 },
    ["Surgery Tools"] = { type = "Tools", weight = 6, price = 96 },
    ["Tarpaulin (4'x6')"] = { type = "Equipment", weight = 10, price = 108 },
    ["Tent, 1-man"] = { type = "Equipment", weight = 25, price = 360 },
    ["Tent, 2-man"] = { type = "Equipment", weight = 35, price = 504 },
    ["Tent, Conical, 3-man"] = { type = "Equipment", weight = 50, price = 648 },
    ["Tinderbox"] = { type = "Equipment", weight = 2, price = 6 },
    ["Torch"] = { type = "Equipment", weight = 1, price = 1 },
    ["Waterskin (2 qt)"] = { type = "Equipment", weight = 1.5, price = 24 },
    ["Beads, Ceramic (12)"] = { type = "Trinkets", weight = 2, price = 6 },
    ["Beads, Glass (12)"] = { type = "Trinkets", weight = 1, price = 12 },
    ["Book Binding (Leather)"] = { type = "Equipment", weight = 1, price = 10 },
    ["Bottle, Ceramic (2 pt)"] = { type = "Container", weight = 1, price = 2 },
    ["Bottle, Glass (2 pt)"] = { type = "Container", weight = 2, price = 6 },
    ["Bowl (8\"x4\")"] = { type = "Container", weight = 3, price = 6 },
    ["Bucket (3 gal)"] = { type = "Container", weight = 10, price = 8 },
    ["Cage (1' cub)"] = { type = "Container", weight = 4, price = 7 },
    ["Candle, Tallow (8 hr)"] = { type = "Equipment", weight = 1, price = 3 },
    ["Censer, Chain"] = { type = "Equipment", weight = 2, price = 24 },
    ["Chain (3 ft)"] = { type = "Equipment", weight = 1, price = 5 },
    ["Charcoal Tinder"] = { type = "Supplies", weight = 4, price = 0.5 },
    ["Crowbar"] = { type = "Tools", weight = 4, price = 9 },
    ["Cup (1 pt)"] = { type = "Container", weight = 1, price = 3 },
    ["Fetters"] = { type = "Equipment", weight = 2, price = 8 },
    ["Goblet, Pewter"] = { type = "Container", weight = 0.4, price = 3 },
    ["Grainflail"] = { type = "Weapon", weight = 4, price = 12 },
    ["Hammer"] = { type = "Tools", weight = 2, price = 5 },
    ["Hourglass"] = { type = "Equipment", weight = 0.3, price = 150 },
    ["Icon, Religious (4\")"] = { type = "Trinkets", weight = 1, price = 2 },
    ["Incense"] = { type = "Supplies", weight = 1, price = 8 },
    ["Ink (1 oz)"] = { type = "Supplies", weight = 0.05, price = 4 },
    ["Inkwell (2 oz)"] = { type = "Container", weight = 1, price = 30 },
    ["Jar (1 pt)"] = { type = "Container", weight = 0.75, price = 6 },
    ["Jar, Lidded (1 qt)"] = { type = "Container", weight = 2, price = 5 },
    ["Jug (1 gal)"] = { type = "Container", weight = 5, price = 9 },
    ["Knife"] = { type = "Weapon", weight = 1, price = 6 },
    ["Maul, Wooden"] = { type = "Weapon", weight = 5, price = 12 },
    ["Oil, Cinnamon"] = { type = "Supplies", weight = 0.06, price = 60 },
    ["Oil, Myrtle"] = { type = "Supplies", weight = 0.06, price = 25 },
    ["Oil, Rose"] = { type = "Supplies", weight = 0.06, price = 20 },
    ["Padlock, Cmp 1"] = { type = "Equipment", weight = 2, price = 12 },
    ["Pan, Copper"] = { type = "Equipment", weight = 2, price = 18 },
    ["Parchment (10\"x14\")"] = { type = "Supplies", weight = 0.02, price = 2 },
    ["Pen, Quill"] = { type = "Equipment", weight = 0.05, price = 2 },
    ["Perfume, Cheap"] = { type = "Supplies", weight = 0.06, price = 12 },
    ["Perfume, Nice"] = { type = "Supplies", weight = 0.06, price = 120 },
    ["Perfume, Typical"] = { type = "Supplies", weight = 0.06, price = 48 },
    ["Pickaxe"] = { type = "Weapon", weight = 5, price = 12 },
    ["Pitchfork"] = { type = "Weapon", weight = 4, price = 9 },
    ["Plate, Ceramic (8\")"] = { type = "Equipment", weight = 2, price = 3 },
    ["Plate, Pewter"] = { type = "Equipment", weight = 0.5, price = 5 },
    ["Plate, Tin"] = { type = "Equipment", weight = 0.5, price = 6 },
    ["Ploughshare"] = { type = "Tools", weight = 12, price = 36 },
    ["Pot (2 qt)"] = { type = "Container", weight = 4, price = 4 },
    ["Scythe"] = { type = "Weapon", weight = 6, price = 16 },
    ["Sickle"] = { type = "Weapon", weight = 2, price = 10 },
    ["Soap"] = { type = "Supplies", weight = 0.06, price = 2 },
    ["Spade"] = { type = "Equipment", weight = 7, price = 8 },
    ["Spikes/Nails (24)"] = { type = "Supplies", weight = 1, price = 3 },
    ["Urn (5 gal)"] = { type = "Container", weight = 9, price = 12 },
    ["Vase"] = { type = "Container", weight = 2, price = 4 },
    ["Vial (4oz) (2\"x5\")"] = { type = "Container", weight = 0.25, price = 4 },
    ["Whip"] = { type = "Weapon", weight = 2, price = 12 },
    ["Battleaxe"] = { type = "Weapon", weight = 6, price = 108 },
    ["Handaxe"] = { type = "Weapon", weight = 4, price = 84 },
    ["Hatchet"] = { type = "Weapon", weight = 3, price = 6 },
    ["Shorkana"] = { type = "Weapon", weight = 2, price = 48 },
    ["Warhammer"] = { type = "Weapon", weight = 4, price = 84 },
    ["Wood Axe"] = { type = "Weapon", weight = 5, price = 12 },
    ["Club"] = { type = "Weapon", weight = 3, price = 12 },
    ["Mace"] = { type = "Weapon", weight = 4, price = 108 },
    ["Maul, Metal"] = { type = "Weapon", weight = 7, price = 96 },
    ["Morning Star"] = { type = "Weapon", weight = 5, price = 48 },
    ["Stick"] = { type = "Weapon", weight = 1, price = 6 },
    ["Ball and Chain"] = { type = "Weapon", weight = 4, price = 72 },
    ["Net"] = { type = "Weapon", weight = 4, price = 48 },
    ["Warflail"] = { type = "Weapon", weight = 5, price = 60 },
    ["Dagger"] = { type = "Weapon", weight = 1, price = 24 },
    ["Keltan"] = { type = "Weapon", weight = 2, price = 36 },
    ["Longknife"] = { type = "Weapon", weight = 2, price = 96 },
    ["Taburi"] = { type = "Weapon", weight = 1, price = 20 },
    ["Falcastra"] = { type = "Weapon", weight = 6, price = 24 },
    ["Glaive"] = { type = "Weapon", weight = 6, price = 60 },
    ["Javelin"] = { type = "Weapon", weight = 3, price = 36 },
    ["Jousting Pole"] = { type = "Weapon", weight = 6, price = 40 },
    ["Lance"] = { type = "Weapon", weight = 7, price = 20 },
    ["Pike"] = { type = "Weapon", weight = 10, price = 96 },
    ["Poleaxe"] = { type = "Weapon", weight = 7, price = 96 },
    ["Spear"] = { type = "Weapon", weight = 4, price = 60 },
    ["Staff"] = { type = "Weapon", weight = 3, price = 24 },
    ["Trident"] = { type = "Weapon", weight = 6, price = 72 },
    ["Buckler"] = { type = "Weapon", weight = 3, price = 30 },
    ["Kite Shield"] = { type = "Weapon", weight = 7, price = 72 },
    ["Knight's Shield"] = { type = "Weapon", weight = 5, price = 60 },
    ["Roundshield"] = { type = "Weapon", weight = 6, price = 48 },
    ["Tower Shield"] = { type = "Weapon", weight = 8, price = 96 },
    ["Bastard Sword"] = { type = "Weapon", weight = 5, price = 184 },
    ["Battlesword"] = { type = "Weapon", weight = 7, price = 240 },
    ["Broadsword"] = { type = "Weapon", weight = 3, price = 156 },
    ["Estoc"] = { type = "Weapon", weight = 3, price = 168 },
    ["Falchion"] = { type = "Weapon", weight = 3, price = 120 },
    ["Scimitar"] = { type = "Weapon", weight = 3, price = 184 },
    ["Shortsword"] = { type = "Weapon", weight = 2, price = 96 },
    ["Mang"] = { type = "Weapon", weight = 3, price = 108 },
    ["Mankar"] = { type = "Weapon", weight = 2, price = 84 },
    ["Composite Bow-150"] = { type = "Missile", weight = 2, price = 72 },
    ["Composite Bow-180"] = { type = "Missile", weight = 2, price = 78 },
    ["Composite Bow-210"] = { type = "Missile", weight = 3, price = 84 },
    ["Composite Bow-240"] = { type = "Missile", weight = 3, price = 90 },
    ["Composite Bow-270"] = { type = "Missile", weight = 4, price = 96 },
    ["Composite Bow-300"] = { type = "Missile", weight = 4, price = 102 },
    ["Longbow-150"] = { type = "Missile", weight = 2, price = 36 },
    ["Longbow-180"] = { type = "Missile", weight = 2, price = 45 },
    ["Longbow-210"] = { type = "Missile", weight = 3, price = 54 },
    ["Longbow-240"] = { type = "Missile", weight = 3, price = 63 },
    ["Longbow-270"] = { type = "Missile", weight = 4, price = 72 },
    ["Longbow-300"] = { type = "Missile", weight = 4, price = 81 },
    ["Composite Crossbow-270"] = { type = "Missile", weight = 7, price = 144 },
    ["Composite Crossbow-300"] = { type = "Missile", weight = 9, price = 204 },
    ["Wooden Crossbow-180"] = { type = "Missile", weight = 3, price = 60 },
    ["Wooden Crossbow-210"] = { type = "Missile", weight = 4, price = 84 },
    ["Wooden Crossbow-240"] = { type = "Missile", weight = 5, price = 96 },
    ["Kuzhan Steelbow"] = { type = "Missile", weight = 12, price = 288 },
    ["Hand Sling"] = { type = "Missile", weight = 0.2, price = 6 },
    ["Staff Sling"] = { type = "Missile", weight = 3, price = 18 },
    ["Bullet, Lead"] = { type = "Ammo", weight = 2, price = 9 },
    ["Bullet, Stone"] = { type = "Ammo", weight = 2, price = 0 },
    ["Belt and Claw"] = { type = "Tools", weight = 2, price = 10 },
    ["Lever"] = { type = "Tools", weight = 3, price = 25 },
    ["Windlass"] = { type = "Tools", weight = 5, price = 60 },
    ["Arrows,Heavy Bodkin (12)"] = { type = "Ammo", weight = 2.6, price = 15 },
    ["Arrows,Heavy Blunt (12)"] = { type = "Ammo", weight = 2.6, price = 15 },
    ["Arrows,Heavy Broad (12)"] = { type = "Ammo", weight = 2.6, price = 15 },
    ["Arrows,Light Bodkin (12"] = { type = "Ammo", weight = 1.5, price = 12 },
    ["Arrows,Light Blunt (12"] = { type = "Ammo", weight = 1.5, price = 12 },
    ["Arrows,Light Broad (12"] = { type = "Ammo", weight = 1.5, price = 12 },
    ["Bolts,Heavy Bodkin (12)"] = { type = "Ammo", weight = 2.6, price = 15 },
    ["Bolts,Heavy Blunt (12)"] = { type = "Ammo", weight = 2.6, price = 15 },
    ["Bolts,Heavy Broad (12)"] = { type = "Ammo", weight = 2.6, price = 15 },
    ["Bolts,Light Bodkin (12"] = { type = "Ammo", weight = 1.5, price = 12 },
    ["Bolts,Light Blunt (12"] = { type = "Ammo", weight = 1.5, price = 12 },
    ["Bolts,Light Broad (12"] = { type = "Ammo", weight = 1.5, price = 12 },
};

function lookupItem(sName)
    if not sName or sName == "" then return nil; end
    
    local sLowerName = sName:lower();
    local nLen = #sLowerName;
    
    -- First try exact match (case-insensitive)
    for k, v in pairs(aEquipmentData) do
        if k:lower() == sLowerName then
            return v, k;
        end
    end
    
    -- If no exact match, try prefix match (if input is at least 3 chars)
    if nLen >= 3 then
        for k, v in pairs(aEquipmentData) do
            if k:lower():sub(1, nLen) == sLowerName then
                return v, k;
            end
        end
    end
    
    return nil;
end
